# vim: set ts=2 sw=2 et :
window:
  dimensions:
    columns: 85
    lines: 48
background_opacity: 0.9
font:
  size: 18

  normal:
    family: Source Han Code JP
    style: Regular

  bold:
    family: Source Han Code JP
    style: Bold

  italic:
    family: Source Han Code JP
  style: Italic

  bold_italic:
    family: Source Han Code JP
    style: Bold Italic

shell:
  program: screen

# Colors (Blood Moon)
colors:
  # Default colors
  primary:
    background: '#10100E'
    foreground: '#C6C6C4'

  # Normal colors
  normal:
    black:   '#10100E'
    red:     '#C40233'
    green:   '#009F6B'
    yellow:  '#FFD700'
    blue:    '#0087BD'
    magenta: '#9A4EAE'
    cyan:    '#20B2AA'
    white:   '#C6C6C4'

  # Bright colors
  bright:
    black:   '#696969'
    red:     '#FF2400'
    green:   '#03C03C'
    yellow:  '#FDFF00'
    blue:    '#007FFF'
    magenta: '#FF1493'
    cyan:    '#00CCCC'
    white:   '#FFFAFA'
