# vim: tabstop=8 expandtab shiftwidth=2 softtabstop=2

[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'cespare/vim-toml'

[[plugins]]
repo = 'vim-jp/vimdoc-ja'

[[plugins]]
repo = 'junegunn/fzf'
hook_post_update = '''
  call fzf#install()
'''

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'airblade/vim-gitgutter'

#[[plugins]]
#repo = 'Shougo/vimproc.vim'
#build = 'make'

#[[plugins]]
#repo = 'thinca/vim-quickrun'
#depends = 'Shougo/vimproc.vim'
#hook_add = '''
#  nnoremap <Leader>q :QuickRun<CR>
#  " https://qiita.com/uplus_e10/items/2a75fbe3d80063eb9c18
#  let g:quickrun_config = get(g:, 'quickrun_config', {})
#  let g:quickrun_config._ = {
#    \ 'runner'    : 'vimproc',
#    \ 'runner/vimproc/updatetime' : 60,
#    \ 'outputter' : 'error',
#    \ 'outputter/error/success' : 'buffer',
#    \ 'outputter/error/error'   : 'quickfix',
#    \ 'outputter/buffer/split'  : ':rightbelow 8sp',
#    \ 'outputter/buffer/close_on_empty' : 1,
#    \ }
#'''

#[[plugins]]
#repo = 'janko-m/vim-test'

#[[plugins]]
#repo = 'kovisoft/slimv'
#hook_add = '''
#  let g:slimv_swank_cmd = '! screen -d -m -t REPL-CCL ccl --load ' . g:dein_dir . '/repos/github.com/kovisoft/slimv/slime/start-swank.lisp'
#'''

[[plugins]]
repo = 'l04m33/vlime'
rtp = 'vim/'

[[plugins]]
repo = 'bhurlow/vim-parinfer'
